---
refresh_interval: 15 # seconds
urls:
- https://direct.playstation.com/en-us/consoles/console/playstation5-console.3005816 # begin PS5 list
- https://direct.playstation.com/en-us/consoles/console/playstation5-digital-edition-console.3005817
- https://www.amazon.com/PlayStation-5-Console/dp/B08FC5L3RG
- https://www.amazon.com/PlayStation-5-Digital/dp/B08FC6MR62
- https://www.bestbuy.com/site/sony-playstation-5-console/6426149.p?skuId=6426149
- https://www.bestbuy.com/site/sony-playstation-5-digital-edition-console/6430161.p?skuId=6430161
- https://www.gamestop.com/video-games/playstation-5/consoles/products/playstation-5/11108140.html?condition=New
- https://www.gamestop.com/video-games/playstation-5/consoles/products/playstation-5-digital-edition/11108141.html?condition=New
- https://www.newegg.com/p/N82E16868110292
- https://www.target.com/p/playstation-5-console/-/A-81114595
- https://www.target.com/p/playstation-5-digital-edition-console/-/A-81114596
- https://www.walmart.com/ip/Sony-PlayStation-5/363472942
- https://www.walmart.com/ip/Sony-PlayStation-5-Digital-Edition/493824815 # end PS5 list
- https://www.amazon.com/Xbox-X/dp/B08H75RTZ8 # begin Xbox list
- https://www.bestbuy.com/site/microsoft-xbox-series-x-1tb-console-black/6428324.p?skuId=6428324
- https://www.gamestop.com/video-games/xbox-series-x/consoles/products/xbox-series-x/B224744V.html
- https://www.newegg.com/p/N82E16868105273
- https://www.target.com/p/xbox-series-x-console/-/A-80790841
- https://www.walmart.com/ip/Xbox-Series-X/443574645 # end Xbox list
...
